bt_navigator:
  ros__parameters:
    use_sim_time: False
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odom
    bt_loop_duration: 10
    default_server_timeout: 20
    enable_groot_monitoring: True
    groot_zmq_publisher_port: 1666
    groot_zmq_server_port: 1667
    plugin_lib_names:
    - nav2_compute_path_to_pose_action_bt_node
    - nav2_compute_path_through_poses_action_bt_node
    - nav2_follow_path_action_bt_node
    - nav2_back_up_action_bt_node
    - nav2_spin_action_bt_node
    - nav2_wait_action_bt_node
    - nav2_clear_costmap_service_bt_node
    - nav2_is_stuck_condition_bt_node
    - nav2_goal_reached_condition_bt_node
    - nav2_goal_updated_condition_bt_node
    - nav2_initial_pose_received_condition_bt_node
    - nav2_reinitialize_global_localization_service_bt_node
    - nav2_rate_controller_bt_node
    - nav2_distance_controller_bt_node
    - nav2_speed_controller_bt_node
    - nav2_truncate_path_action_bt_node
    - nav2_goal_updater_node_bt_node
    - nav2_recovery_node_bt_node
    - nav2_pipeline_sequence_bt_node
    - nav2_round_robin_node_bt_node
    - nav2_transform_available_condition_bt_node
    - nav2_time_expired_condition_bt_node
    - nav2_distance_traveled_condition_bt_node
    - nav2_single_trigger_bt_node
    - nav2_is_battery_low_condition_bt_node
    - nav2_navigate_through_poses_action_bt_node
    - nav2_navigate_to_pose_action_bt_node
    - nav2_remove_passed_goals_action_bt_node
    - nav2_planner_selector_bt_node
    - nav2_controller_selector_bt_node
    - nav2_goal_checker_selector_bt_node

bt_navigator_rclcpp_node:
  ros__parameters:
    use_sim_time: False
controller_server:
  ros__parameters:
    controller_frequency: 25.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    progress_checker_plugins: ["progress_checker"]
    goal_checker_plugins: ["goal_checker"]
    controller_plugins: ["FollowPath"]

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.15
      stateful: True

    # DWB parameters
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: True
      min_vel_x: -2.8
      min_vel_y: -2.8
      max_vel_x: 2.8
      max_vel_y: 2.8
      max_vel_theta: 0.7 #最大角速度
      min_speed_xy: -2.8
      max_speed_xy: 2.8 #最大平移速度
      min_speed_theta: 0.0
      # Add high threshold velocity for turtlebot 3 issue.
      # https://github.com/ROBOTIS-GIT/turtlebot3_simulations/issues/75
      acc_lim_x: 3.0
      acc_lim_y: 3.0
      acc_lim_theta: 2.5
      decel_lim_x: -3.0
      decel_lim_y: -3.0
      decel_lim_theta: -2.5
      vx_samples: 15
      vy_samples: 15
      vtheta_samples: 10
      sim_time: 1.2
      linear_granularity: 0.05
      angular_granularity: 0.025
      transform_tolerance: 0.2
      xy_goal_tolerance: 0.25
      trans_stopped_velocity: 0.25
      short_circuit_trajectory_evaluation: True
      stateful: True
      critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]
      BaseObstacle.scale: 0.02
      PathAlign.scale: 32.0
      PathAlign.forward_point_distance: 0.1
      GoalAlign.scale: 24.0
      GoalAlign.forward_point_distance: 0.1
      PathDist.scale: 32.0
      GoalDist.scale: 32.0
      RotateToGoal.scale: 24.0
      RotateToGoal.slowing_factor: 4.0
      RotateToGoal.lookahead_time: -1.0

local_costmap: #\BEֲ\BF\B4\FA\BC۵\D8ͼ
  local_costmap:
    ros__parameters:
      update_frequency: 20.0 #20.0 #10.0 # \B4\FA\BC۵\D8ͼ\B8\FC\D0µ\C4Ƶ\C2\CA
      publish_frequency: 10.0 #1.0 #\B7\A2\B2\BC\B4\FA\BC۵\D8ͼ\B5\C4Ƶ\C2\CA
      global_frame: map #ȫ\BE\D6\D7\F8\B1\EAϵ\B5\C4\C3\FB\D7\D6
      robot_base_frame: base_link #\BB\FA\C6\F7\C8˵\D7\C5\CC\D7\F8\B1\EAϵ\B5\C4\C3\FB\D7\D6
      use_sim_time: False
      rolling_window: true # costmap \CAǷ\F1Ӧ\B8\C3\D3\EB\BB\FA\C6\F7\C8˵\D7\C5\CCһ\C6\F0\B9\F6\B6\AF
      width: 6 #3
      height: 6 #3#\BEֲ\BF\B4\FA\BC۵\D8ͼ\B5Ŀ\ED\B8\DF
      resolution: 0.05 #\BEֲ\BF\B4\FA\BC۵\D8ͼ1\CF\F1\CBصķֱ\E6\C2ʣ\AC\B5\A5λm
      robot_radius: 0.35 #\BB\FA\C6\F7\C8˵İ뾶
      # footprint: "[ [0.3, 0.25], [0.3, -0.25], [-0.3, -0.25], [-0.3, 0.25] ]"
      footprint_padding: 0.05 #0.5 #\D0\E8Ҫ\CC\EE\B3\E4\B5\C4ռλ\B7\FB\B4\F3С
      plugins: ["obstacle_layer", "inflation_layer","voxel_layer"]
      inflation_layer: #\C5\F2\D5Ͳ\E3
        plugin: "nav2_costmap_2d::InflationLayer"
        # enabled: True #\CAǷ\F1\C6\F4\D3\C3
        cost_scaling_factor: 1.0 #10.0 #3.0 #\C5\F2\D5Ͱ뾶\C9ϵ\C4ָ\CA\FD˥\BC\F5\D2\F2\D7\D3
        inflation_radius: 0.45 #0.35 #\C0\A9\B4\F3\D6\C2\C3\FC\D5ϰ\AD\CE\EF\D6\DCΧ\B5ĳɱ\BE\B5\D8ͼ\B5İ뾶
      obstacle_layer: # \D5ϰ\AD\CE\EF\B2\E3
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True #\CAǷ\F1\C6\F4\D3\C3
        observation_sources: scan #\CA\FD\BE\DDԴ\B5\C4\C3\FC\C3\FB\BFռ\E4
        max_obstacle_height: 2.0 #1.0 #\CF\F2ռ\D3\C3\CD\F8\B8\F1\CC\ED\BCӷ\B5\BBص\C4\D7\EE\B4\F3\B8߶\C8
        min_obstacle_height: -2.0 #-1.0 #\CF\F2ռ\D3\C3\CD\F8\B8\F1\CC\ED\BCӷ\B5\BBص\C4\D7\EEС\B8߶\C8
        scan:
          topic: /scan
          max_obstacle_height: 1.0
          min_obstacle_height: -1.0
          inf_is_valid: true
          clearing: True # source \CAǷ\F1Ӧ\D4\DAcostmap\D6\D0\C7\E5\B3\FDraytrace
          marking: True # \C0\B4Դ\CAǷ\F1Ӧ\D4\DAcostmap\D6б\EA\BC\C7
          data_type: "LaserScan" #\CA\E4\C8\EB\CA\FD\BE\DD\C0\E0\D0\CD
          raytrace_max_range: 30.0 #9.0 #5.0 #3.0 #\B4\D3costmap\B5\BDraytrace\C7\E5\B3\FD\D5ϰ\AD\CE\EF\B5\C4\D7\EE\B4\F3\B7\B6Χ
          raytrace_min_range: 0.0 #\B4\D3costmap\B5\BDraytrace\C7\E5\B3\FD\D5ϰ\AD\CE\EF\B5\C4\D7\EEС\B7\B6Χ
          obstacle_max_range: 10.5 #4.0 #2.5 # \D4\DAcostmap\D6б\EA\BC\C7\D5ϰ\AD\B5\C4\D7\EE\B4\F3\B7\B6Χ
          obstacle_min_range: 0.0 # \D4\DAcostmap\D6б\EA\BC\C7\D5ϰ\AD\B5\C4\D7\EEС\B7\B6Χ
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        footprint_clearing_enabled: true
        publish_voxel_map: False
        origin_z: 0.0
        z_resolution: 0.2
        z_voxels: 12
        mark_threshold: 1
        observation_sources: livox
        min_obstacle_height: 0.00
        max_obstacle_height: 2.0
        livox:
          topic: /segmentation/obstacle
          obstacle_max_range: 10.0
          obstacle_min_range: 0.0
          raytrace_min_range: 0.0
          raytrace_max_range: 20.0
          max_obstacle_height: 1.0
          min_obstacle_height: -1.0
          inf_is_valid: true
          clearing: True
          marking: True
          data_type: "PointCloud2"

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 10.0
      publish_frequency: 15.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: False
      robot_radius: 0.35
      resolution: 0.05
      track_unknown_space: true
      plugins: ["static_layer", "obstacle_layer","inflation_layer","voxel_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 1.0
          min_obstacle_height: -1.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          inf_is_valid: true
          raytrace_max_range: 30.0
          raytrace_min_range: 0.0
          obstacle_max_range: 3.3
          obstacle_min_range: 0.0
          min_obstacle_height: -0.54 #0.0
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        footprint_clearing_enabled: true
        publish_voxel_map: False
        origin_z: 0.0
        z_resolution: 0.2
        z_voxels: 12
        mark_threshold: 1
        observation_sources: livox
        min_obstacle_height: 0.00
        max_obstacle_height: 2.0
        livox:
          topic: /segmentation/obstacle
          obstacle_max_range: 10.0
          obstacle_min_range: 0.0
          raytrace_min_range: 0.0
          raytrace_max_range: 20.0
          max_obstacle_height: 1.0
          min_obstacle_height: -1.0
          inf_is_valid: true
          clearing: True
          marking: True
          data_type: "PointCloud2"
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 1.0
        inflation_radius: 0.45 #0.55
      always_send_full_costmap: True

map_server:
  ros__parameters :
    use_sim_time: False
    # Overridden in launch by the "map" launch configuration or provided default value.
    # To use in yaml, remove the default "map" value in the tb3_simulation_launch.py file & provide full path to map below.
    yaml_filename: ""

map_saver:
  ros__parameters:
    use_sim_time: False
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: True

# planner_server:
#   ros__parameters:
#     expected_planner_frequency: 20.0
#     use_sim_time: False
#     planner_plugins: ["GridBased"]
#     GridBased:
#       plugin: "nav2_theta_star_planner/ThetaStarPlanner"
#       how_many_corners: 8
#       w_euc_cost: 1.0
#       w_traversal_cost: 2.0
#       w_heuristic_cost: 1.0

planner_server:
  ros__parameters:
    planner_plugins: ['GridBased']
    GridBased:
      plugin: 'nav2_navfn_planner/NavfnPlanner'
      use_astar: True
      allow_unknown: True
      tolerance: 1.0

planner_server_rclcpp_node:
  ros__parameters:
    use_sim_time: False

smoother_server:
  ros__parameters:
    use_sim_time: False
    smoother_plugins: ["simple_smoother"]
    simple_smoother:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 1.0e-10
      max_its: 1000
      do_refinement: True

behavior_server:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    behavior_plugins: ["spin", "backup", "drive_on_heading", "assisted_teleop", "wait"]
    spin:
      plugin: "nav2_behaviors/Spin"
    backup:
      plugin: "nav2_behaviors/BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors/DriveOnHeading"
    wait:
      plugin: "nav2_behaviors/Wait"
    assisted_teleop:
      plugin: "nav2_behaviors/AssistedTeleop"
    global_frame: odom
    robot_base_frame: base_link
    transform_tolerance: 0.1
    use_sim_time: False
    simulate_ahead_time: 2.0
    max_rotational_vel: 0.8
    min_rotational_vel: 0.3
    rotational_acc_lim: 3.2

robot_state_publisher:
  ros__parameters:
    use_sim_time: False

waypoint_follower:
  ros__parameters:
    use_sim_time: False
    loop_rate: 20
    stop_on_failure: false
    waypoint_task_executor_plugin: "wait_at_waypoint"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      waypoint_pause_duration: 200

velocity_smoother:
  ros__parameters:
    use_sim_time: False
    smoothing_frequency: 20.0
    scale_velocities: False
    feedback: "OPEN_LOOP"
    max_velocity: [5.5, 0.0, 7.8]
    min_velocity: [-5.5, 0.0, -7.8]
    max_accel: [5.5, 0.0, 7.2]
    max_decel: [-5.5, 0.0, -7.2]
    odom_topic: "odom"
    odom_duration: 0.1
    deadband_velocity: [0.0, 0.0, 0.0]
    velocity_timeout: 1.0













